# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170222_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='home_page_status',
            field=models.BooleanField(default=True, verbose_name='Ana səhifədə görünsün?'),
        ),
    ]
