# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_home_page_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqqimizda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
        ),
    ]
